name: DAC
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - ca-certificates=2024.12.14
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - ipykernel=6.14.0
  - ipython=7.33.0
  - jedi=0.18.2
  - jupyter_client=7.0.6
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.14
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - ptyprocess=0.7.0
  - pygments=2.18.0
  - python=3.8.19
  - python_abi=3.8
  - readline=8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
    - accelerate==0.34.0
    - addict==2.4.0
    - aiohappyeyeballs==2.4.0
    - aiohttp==3.10.5
    - aiosignal==1.3.1
    - aliyun-python-sdk-core==2.15.2
    - aliyun-python-sdk-kms==2.16.5
    - annotated-types==0.7.0
    - anthropic==0.49.0
    - anyio==4.4.0
    - async-timeout==4.0.3
    - attrs==24.2.0
    - auto-gptq==0.7.1
    - categories==0.3.7
    - certifi==2025.7.14
    - cffi==1.17.1
    - charset-normalizer==3.4.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - coloredlogs==15.0.1
    - contourpy==1.1.1
    - crcmod==1.7
    - cryptography==43.0.1
    - cycler==0.12.1
    - datasets==3.0.0
    - deepspeed==0.16.2
    - dill==0.3.8
    - diskcache==5.6.3
    - distro==1.9.0
    - einops==0.8.0
    - evaluate==0.4.3
    - exceptiongroup==1.2.2
    - fastapi==0.112.4
    - filelock==3.16.1
    - fonttools==4.53.1
    - frozenlist==1.4.1
    - fschat==0.2.36
    - fsspec==2025.3.0
    - fuzzywuzzy==0.18.0
    - gekko==1.2.1
    - gguf==0.10.0
    - h11==0.14.0
    - hf-xet==1.1.5
    - hjson==3.1.0
    - httpcore==1.0.5
    - httptools==0.6.1
    - httpx==0.27.0
    - huggingface-hub==0.34.1
    - humanfriendly==10.0
    - idna==3.10
    - imbalanced-learn==0.12.4
    - imblearn==0.0
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - interegular==0.3.3
    - isal==1.7.1
    - jieba==0.42.1
    - jinja2==3.1.4
    - jiter==0.5.0
    - jmespath==0.10.0
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.7
    - lark==1.2.2
    - lightning-utilities==0.11.9
    - llmlingua==0.2.2
    - llvmlite==0.41.1
    - lm-format-enforcer==0.10.6
    - markdown-it-py==3.0.0
    - markdown2==2.5.1
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mdurl==0.1.2
    - mistral-common==1.4.3
    - modelscope==1.17.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - msgspec==0.18.6
    - multidict==6.1.0
    - multiprocess==0.70.16
    - networkx==3.1
    - nh3==0.2.21
    - ninja==1.11.1.3
    - nltk==3.9.1
    - numba==0.58.1
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.560.30
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.20
    - nvidia-nvtx-cu12==12.1.105
    - openai==1.7.0
    - optimum==1.23.3
    - oss2==2.19.0
    - outlines==0.0.46
    - packaging==25.0
    - pandas==2.0.3
    - partial-json-parser==0.2.1.1.post4
    - peft==0.13.2
    - pillow==10.4.0
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.21.0
    - prometheus-fastapi-instrumentator==7.0.0
    - protobuf==5.28.2
    - psutil==6.0.0
    - py-cpuinfo==9.0.0
    - pyairports==2.1.1
    - pyarrow==17.0.0
    - pycountry==24.6.1
    - pycparser==2.22
    - pycryptodome==3.20.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydantic-settings==2.8.1
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - ray==2.10.0
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.4
    - rich==14.0.0
    - rouge==1.0.1
    - rpds-py==0.20.0
    - safetensors==0.5.3
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - shortuuid==1.0.13
    - sniffio==1.3.1
    - starlette==0.38.6
    - svgwrite==1.4.3
    - sympy==1.13.2
    - tensor-parallel==2.0.0
    - threadpoolctl==3.5.0
    - tiktoken==0.7.0
    - tokenizers==0.20.3
    - torch==2.4.0
    - torchaudio==2.4.0
    - torchmetrics==1.5.2
    - torchvision==0.19.0
    - tqdm==4.67.1
    - transformers==4.45.1
    - triton==3.0.0
    - typing-extensions==4.13.2
    - tzdata==2024.1
    - urllib3==2.2.3
    - uvicorn==0.31.0
    - uvloop==0.20.0
    - vllm==0.6.2
    - watchfiles==0.24.0
    - wavedrom==2.0.3.post3
    - websockets==13.1
    - xformers==0.0.27.post2
    - xopen==2.0.2
    - xxhash==3.5.0
    - yarl==1.11.1
    - zipp==3.20.2
    - zlib-ng==0.5.1

